cinst -y fiddler4
cinst -y git
cinst -y git-credential-winstore
cinst -y vim
cinst -y dotpeek
cinst -y Devbox-RapidEE
cinst -y notepadplusplus
cinst -y 7zip
cinst -y Firefox
cinst -y putty
cinst -y keepass
cinst -y opera
cinst -y chrome
cinst -y beyondcompare
cinst -y lessmsi
cinst -y speccy
cinst -y rdcman
cinst -y lockhunter
cinst -y filebot
cinst -y ilspy
cinst -y procmon